import type { Metadata } from "next";
// import localFont from "next/font/local"; // If fonts were present locally
import "./globals.css";

export const metadata: Metadata = {
  title: "Class 11 - Server Actions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
